printWidth: 80
tabWidth: 2
useTabs: false

semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false

trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: always

proseWrap: always
htmlWhitespaceSensitivity: ignore

# PHP
phpVersion: "8.1"
braceStyle: 1tbs
trailingCommaPHP: true